management:
  endpoints:
    enabled-by-default: true #暴露所有端点信息
    web:
      exposure:
        include: '*'  #以web方式暴露


server:
  port: 8888
  servlet:
    context-path: /hello

myhello:
  start: nihao
  end: bye
