sever:
  port: 8080


#myhello:
#  start: nihao
#  end: bye
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/silk_dormitory?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp


mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    resources:
      mapper: debug




